export const propertyMapping = {
  name: "name",
  email: "email",
  phone: "phone",
  gender: "gender",
  address: "address",
  city: "city",
  state: "state",
  zip: "zip",
  notes: "notes",
  role: "role",
  abbreviation: "abbreviation",
  weekend: "weekendNo",
  description: "description",
  "notes (optional)": "notes",
  "date begin": "dateBegin",
  "date end": "dateEnd",
  "weekend no": "weekendNo",
  "description (optional)": "description",
  "lay director": "layDirector",
  "date begin (dd-mm-yyyy)": "dateBegin",
  "date end (dd-mm-yyyy)": "dateEnd",
};
